In [11]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print("1D array:",arr1)
arr2=np.array([[1,2,3],[4,5,6]])
print("2D array:",arr2)
arr3=np.array([[[1,2],[3,4],[5,6]]])
print("3D array:",arr3)
a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])
print("addition:",a+b)
print("subtraction:",a-b)
print("multiply:",a*b)
print("divide:",a/b)
arr=np.array([1,2,3,4,5,6,7])
print("mean:",np.mean(arr))
print("sum:",np.sum(arr))
print("standard deviation:",np.std(arr))
new_arr=np.arange(1,10)
print("arange:",new_arr)
print("reshape:",new_arr.reshape(3,3))
print("linspace:",np.linspace(0,10,7))
print("indices of minimum values:",np.argmin(arr))
print("indices of maximum values:",np.argmax(arr))


1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]
3D array: [[[1 2]
  [3 4]
  [5 6]]]
addition: [11 22 33 44 55]
subtraction: [ 9 18 27 36 45]
multiply: [ 10  40  90 160 250]
divide: [10. 10. 10. 10. 10.]
mean: 4.0
sum: 28
standard deviation: 2.0
arange: [1 2 3 4 5 6 7 8 9]
reshape: [[1 2 3]
 [4 5 6]
 [7 8 9]]
linspace: [ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]
indices of minimum values: 0
indices of maximum values: 6
